version: '3.8'

services:
  db:
    image: postgres:14.3
    ports:
      - "5432:5432"  # Asegúrate de que este puerto esté mapeado
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=foo